# Etapa 2 · 01 — Diagnóstico, limpieza y dataset analítico
**TPI Análisis de Datos Masivos — UCASAL 2026** · Problema: *optimización de la logística de última milla (Olist + flota sintética)*

**Qué hace este notebook**
1. Conecta a PostgreSQL y ejecuta el diagnóstico de calidad (`sql/01_diagnostico_calidad.sql`).
2. Crea las vistas analíticas (`sql/02_vistas_analiticas.sql`).
3. Valida el grano del dataset (1 fila por orden) y cuantifica el **impacto de la limpieza** en el volumen.
4. Aplica controles finales en Python (tipos, coherencia de la flota, flags de outliers) y exporta el **dataset analítico**.

> **Prerrequisito:** pipeline de la Etapa 1 ejecutado (flota generada con `generate_fleet_dataset.py`): 14 tablas cargadas (100 vehículos, 95 conductores, 96.470 entregas, 802 mantenimientos, 3.531 incidentes).
>
> **Naturaleza de los datos de flota:** `delivery_status`, `distance_km` y `eta_variation_hours` derivan de datos reales de Olist; las variables operativas (tráfico, clima, riesgo, conductor, incidentes, mantenimiento) son simuladas y están **condicionadas a la realidad por diseño**.

In [1]:
import os, time, pathlib, warnings
import pandas as pd, numpy as np
from sqlalchemy import create_engine, text
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", 60, "display.width", 200, "display.max_colwidth", 90)

# --- Conexión: ajustar usuario/clave o definir la variable de entorno PG_URL ---
PG_URL = os.getenv("PG_URL", "postgresql+psycopg2://postgres:postgres@localhost:5432/olist_logistics_db")
engine = create_engine(PG_URL)

ROOT   = pathlib.Path("..")                  # etapa2-preparacion-eda/
SQLDIR = ROOT / "sql"
OUT    = ROOT / "output"; OUT.mkdir(exist_ok=True)

def q(sql, **kw):
    with engine.connect() as c:
        return pd.read_sql(text(sql), c, **kw)

print(q("select current_database() db, version() v").T)

                                                                          0
db                                                       olist_logistics_db
v   PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35229, 64-bit

## 1. Diagnóstico de calidad (solo lectura)
Ejecuta el script SQL completo y lo trae como DataFrame: una fila por chequeo.

In [2]:
def run_sql_file(path):
    """Ejecuta un .sql que no contiene metacomandos psql (\\timing, \\echo, \\pset)."""
    txt = "\n".join(l for l in pathlib.Path(path).read_text(encoding="utf-8").splitlines()
                    if not l.strip().startswith("\\"))
    return txt

# El script termina con una consulta de detalle (categorías sin traducción): aquí solo se necesita la tabla principal
diag_sql = run_sql_file(SQLDIR / "01_diagnostico_calidad.sql").split("-- ---------- DETALLE")[0]
t0 = time.perf_counter()
diag = q(diag_sql)
print(f"Diagnóstico ejecutado en {time.perf_counter()-t0:.2f} s — {len(diag)} chequeos")
diag.to_csv(OUT / "diagnostico_calidad.csv", index=False)
diag

Diagnóstico ejecutado en 2.32 s — 52 chequeos

,dimension,chequeo,afectados,total,pct,accion
0,categóricas,categorías de producto sin traducción al inglés,3,74,4.054,COALESCE a nombre en portugués (listar con la consulta de detalle al final del script)
1,categóricas,payment_type = not_defined,3,103886,0.003,"Agrupar en ""otro"""
2,categóricas,order_status fuera de catálogo,0,99441,0.000,Debe ser 0
3,categóricas,zip prefix con longitud <> 5 (pérdida de ceros a la izquierda),0,99441,0.000,Debe ser 0 (CHAR(5))
4,categóricas,customer_state fuera de las 27 siglas IBGE,0,99441,0.000,Debe ser 0
5,duplicados,zip prefixes con múltiples coordenadas en geolocation,17972,19015,94.515,Colapsar a 1 centroide por zip (mv_geo_zip)
6,duplicados,órdenes con más de 1 ítem (riesgo de fan-out en JOIN),9803,98666,9.936,Agregar ítems a nivel orden (grano del dataset = 1 fila por orden)
7,duplicados,clientes recurrentes (customer_unique_id con >1 customer_id),2997,96096,3.119,No es error: customer_id cambia por orden. Usar customer_unique_id para recurrencia
8,duplicados,órdenes con más de 1 pago,2961,99440,2.978,Sumar payment_value; payment_type = método del pago 1
9,duplicados,órdenes con más de 1 vendedor,1278,98666,1.295,Tomar el vendedor del ítem 1 como origen del envío
10,duplicados,review_id repetido (filas sobrantes),814,99224,0.820,Usar review_pk; en el dataset se toma la última reseña por orden
11,duplicados,órdenes con más de 1 reseña,547,98673,0.554,Agregar a 1 reseña por orden (la más reciente) para no duplicar filas
12,fechas,órdenes por fuera de 2016-09 … 2018-10 (rango Olist),0,99441,0.000,Informativo
13,fechas,mantenimientos anteriores al año de fabricación del vehículo,0,802,0.000,Debe ser 0
14,fechas,incidentes con fecha fuera del viaje (pickup–delivery),0,3531,0.000,Informativo
15,fechas,conductores con hire_date posterior a su primera entrega,0,95,0.000,Debe ser 0
16,fechas,mantenimientos fuera de 2016-01 … 2018-12,0,802,0.000,Debe ser 0
17,inconsistencias,items con freight_value = 0,383,112650,0.340,Conservar: posible envío gratis
18,inconsistencias,purchase_ts > carrier_date,166,96478,0.172,Excluir: secuencia temporal imposible
19,inconsistencias,carrier_date > customer_date (despacho posterior a entrega),23,96478,0.024,Excluir: secuencia temporal imposible
20,inconsistencias,payments con payment_value = 0,9,103886,0.009,Flaguear
21,inconsistencias,approved_at < purchase_ts,0,99441,0.000,Flaguear
22,inconsistencias,conductor de la entrega con vehículo distinto al de la entrega,0,96470,0.000,Debe ser 0 (1 conductor = 1 vehículo)
23,inconsistencias,"entregas donde la licencia del conductor no habilita el tipo de vehículo (A=moto, B=va...",0,96470,0.000,Debe ser 0 (la licencia es coherente con el vehículo)
24,inconsistencias,delivery_status (flota sintética) vs. demora real Olist: desacuerdo,0,96470,0.000,Debe ser 0 (delivery_status se deriva de la demora real de Olist)
25,inconsistencias,fleet_deliveries: delivery_date <> olist.order_delivered_customer_date,0,96470,0.000,Debe ser 0 (la fuente sintética hereda las fechas de Olist)
26,inconsistencias,estimated_delivery < purchase_ts,0,99441,0.000,Excluir
27,inconsistencias,vehículo asignado inconsistente con peso (regla moto/van/truck),0,96448,0.000,Debe ser 0 (la regla moto/van/truck usa el peso del primer ítem)
28,inconsistencias,items con price = 0,0,112650,0.000,Flaguear y revisar (la vista NO los excluye)
29,integridad,órdenes sin ítems,775,99441,0.779,Excluir del dataset (sin peso/flete)
30,integridad,órdenes delivered sin reseña,646,96478,0.670,Conservar con review_score NULL (LEFT JOIN); excluir solo de KPIs de satisfacción
31,integridad,clientes con zip sin coordenadas en geolocation,278,99441,0.280,distancia_haversine_km = NULL; distance_km sí existe (usa el centroide del estado como...
32,integridad,órdenes delivered sin registro en fleet_deliveries,8,96478,0.008,Excluir (INNER JOIN en el dataset analítico)
33,integridad,ítems apuntando al placeholder unknown_product_placeholder,0,112650,0.000,Excluir peso del cálculo (peso desconocido)
34,integridad,entregas realizadas con vehículo en baja,0,96470,0.000,Debe ser 0 (las bajas no reciben entregas; status es una foto sin fecha)
35,integridad,vehículos con más de 1 conductor (rompe la relación 1:1),0,95,0.000,Debe ser 0 (1 conductor por vehículo activo)
36,integridad,conductores cuyo vehículo está en baja,0,95,0.000,Debe ser 0 (conductores solo en vehículos activos)
37,integridad,fleet_deliveries cuya orden NO está delivered,0,96470,0.000,Debe ser 0
38,nulos,reviews sin comentario (message),58247,99224,58.703,Normal: dato opcional. No imputar
39,nulos,products sin categoría,610,32952,1.851,Imputar categoría = 'sin_categoria'
40,nulos,orders delivered sin order_delivered_customer_date,8,96478,0.008,Excluir del dataset analítico
41,nulos,products sin product_weight_g,3,32952,0.009,Imputar con mediana de la categoría
42,nulos,orders delivered sin order_delivered_carrier_date,2,96478,0.002,Excluir (no se puede calcular tiempo de despacho)
43,outliers,fleet: eta_variation_hours censurado en los límites (=-168 ó =336),6208,96470,6.435,Informativo: la variable está acotada por el generador; este porcentaje es la censura
44,outliers,freight_value > Q3+3·IQR,5538,112650,4.916,Conservar y flaguear (flete real alto en regiones remotas)
45,outliers,product_weight_g > Q3+3·IQR (extremo severo),3073,32952,9.326,Conservar (son pesos reales); ver winsorización solo para modelos
46,outliers,fleet: distance_km censurado en los límites (=5 ó =6000),567,96470,0.588,Informativo: entregas intra-zona (haversine x factor de ruta < 5 km) quedan en el piso...
47,outliers,tiempo de entrega > 60 días,306,96476,0.317,Conservar y flaguear (entregas reales muy tardías)
48,outliers,coordenadas fuera del bounding box de Brasil,42,1000163,0.004,Filtrar al construir mv_geo_zip
49,outliers,product_weight_g = 0,4,32952,0.012,Imputar con mediana de la categoría
50,outliers,"fleet: eta_variation_hours fuera de [-168, 336]",0,96470,0.000,Debe ser 0 (rango declarado)
51,outliers,"fleet: distance_km fuera de [5, 6000]",0,96470,0.000,Debe ser 0 (rango declarado; CHECK chk_del_dist)

In [3]:
# Detalle: categorías de producto sin traducción al inglés (se resuelven con traducción manual en la vista)
q("""SELECT DISTINCT p.product_category_name AS categoria_sin_traduccion
   FROM olist_products p LEFT JOIN product_category_name_translation t USING (product_category_name)
   WHERE p.product_category_name IS NOT NULL AND t.product_category_name IS NULL ORDER BY 1""")

                        categoria_sin_traduccion
0                                       pc_gamer
1  portateis_cozinha_e_preparadores_de_alimentos
2                                        unknown

In [4]:
# Resumen: ¿qué chequeos encontraron problemas?
con_problemas = diag[diag.afectados > 0].sort_values(["dimension","pct"], ascending=[True, False])
print(f"{len(con_problemas)} de {len(diag)} chequeos con hallazgos")
con_problemas[["dimension","chequeo","afectados","total","pct","accion"]]

29 de 52 chequeos con hallazgos

,dimension,chequeo,afectados,total,pct,accion
0,categóricas,categorías de producto sin traducción al inglés,3,74,4.054,COALESCE a nombre en portugués (listar con la consulta de detalle al final del script)
1,categóricas,payment_type = not_defined,3,103886,0.003,"Agrupar en ""otro"""
5,duplicados,zip prefixes con múltiples coordenadas en geolocation,17972,19015,94.515,Colapsar a 1 centroide por zip (mv_geo_zip)
6,duplicados,órdenes con más de 1 ítem (riesgo de fan-out en JOIN),9803,98666,9.936,Agregar ítems a nivel orden (grano del dataset = 1 fila por orden)
7,duplicados,clientes recurrentes (customer_unique_id con >1 customer_id),2997,96096,3.119,No es error: customer_id cambia por orden. Usar customer_unique_id para recurrencia
8,duplicados,órdenes con más de 1 pago,2961,99440,2.978,Sumar payment_value; payment_type = método del pago 1
9,duplicados,órdenes con más de 1 vendedor,1278,98666,1.295,Tomar el vendedor del ítem 1 como origen del envío
10,duplicados,review_id repetido (filas sobrantes),814,99224,0.820,Usar review_pk; en el dataset se toma la última reseña por orden
11,duplicados,órdenes con más de 1 reseña,547,98673,0.554,Agregar a 1 reseña por orden (la más reciente) para no duplicar filas
17,inconsistencias,items con freight_value = 0,383,112650,0.340,Conservar: posible envío gratis
18,inconsistencias,purchase_ts > carrier_date,166,96478,0.172,Excluir: secuencia temporal imposible
19,inconsistencias,carrier_date > customer_date (despacho posterior a entrega),23,96478,0.024,Excluir: secuencia temporal imposible
20,inconsistencias,payments con payment_value = 0,9,103886,0.009,Flaguear
29,integridad,órdenes sin ítems,775,99441,0.779,Excluir del dataset (sin peso/flete)
30,integridad,órdenes delivered sin reseña,646,96478,0.670,Conservar con review_score NULL (LEFT JOIN); excluir solo de KPIs de satisfacción
31,integridad,clientes con zip sin coordenadas en geolocation,278,99441,0.280,distancia_haversine_km = NULL; distance_km sí existe (usa el centroide del estado como...
32,integridad,órdenes delivered sin registro en fleet_deliveries,8,96478,0.008,Excluir (INNER JOIN en el dataset analítico)
38,nulos,reviews sin comentario (message),58247,99224,58.703,Normal: dato opcional. No imputar
39,nulos,products sin categoría,610,32952,1.851,Imputar categoría = 'sin_categoria'
41,nulos,products sin product_weight_g,3,32952,0.009,Imputar con mediana de la categoría
40,nulos,orders delivered sin order_delivered_customer_date,8,96478,0.008,Excluir del dataset analítico
42,nulos,orders delivered sin order_delivered_carrier_date,2,96478,0.002,Excluir (no se puede calcular tiempo de despacho)
45,outliers,product_weight_g > Q3+3·IQR (extremo severo),3073,32952,9.326,Conservar (son pesos reales); ver winsorización solo para modelos
43,outliers,fleet: eta_variation_hours censurado en los límites (=-168 ó =336),6208,96470,6.435,Informativo: la variable está acotada por el generador; este porcentaje es la censura
44,outliers,freight_value > Q3+3·IQR,5538,112650,4.916,Conservar y flaguear (flete real alto en regiones remotas)
46,outliers,fleet: distance_km censurado en los límites (=5 ó =6000),567,96470,0.588,Informativo: entregas intra-zona (haversine x factor de ruta < 5 km) quedan en el piso...
47,outliers,tiempo de entrega > 60 días,306,96476,0.317,Conservar y flaguear (entregas reales muy tardías)
49,outliers,product_weight_g = 0,4,32952,0.012,Imputar con mediana de la categoría
48,outliers,coordenadas fuera del bounding box de Brasil,42,1000163,0.004,Filtrar al construir mv_geo_zip

### Lectura del diagnóstico
Resumen para `docs/informe_calidad_datos.md`:
- **Hallazgos sobre Olist (datos reales):** 42 coordenadas fuera de Brasil, 4 productos con peso 0, 814 `review_id` duplicados, 8 órdenes `delivered` sin `fleet_deliveries`, 166 + 23 secuencias de fechas imposibles.
- **Chequeos de la flota que deben dar 0:** desacuerdo `delivery_status` vs demora real, conductor con vehículo distinto al de la entrega, licencia que no habilita el vehículo, entregas con vehículo en baja, vehículos con más de un conductor, fechas de mantenimiento / contratación / incidentes, y rangos de `distance_km` [5, 6000] y `eta_variation_hours` [-168, 336].
- **Chequeos informativos de la flota:** `distance_km` censurada en el piso de 5 km (entregas intra-zona) y `eta_variation_hours` censurada en los límites (≈ 6,4 %: la variable está acotada por el generador).
- Las **duplicaciones por ítems/pagos/reseñas** no son errores: son relaciones 1:N que, mal unidas, inflan filas y KPIs. Se resuelven agregando a nivel orden.

## 2. Construcción del dataset analítico (vistas SQL)

In [5]:
views_sql = run_sql_file(SQLDIR / "02_vistas_analiticas.sql")
t0 = time.perf_counter()
with engine.begin() as c:
    c.exec_driver_sql(views_sql)
print(f"Vistas creadas en {time.perf_counter()-t0:.1f} s")
q("select matviewname, ispopulated from pg_matviews where schemaname='public'")

Vistas creadas en 15.3 s

            matviewname  ispopulated
0            mv_geo_zip         True
1  mv_dataset_analitico         True

## 3. Validación del grano y trazabilidad del volumen (embudo de filas)

In [6]:
embudo = q("""
WITH base AS (SELECT * FROM olist_orders)
SELECT '1. Órdenes totales'                                  AS paso, COUNT(*) AS filas FROM base
UNION ALL SELECT '2. status = delivered',                    COUNT(*) FROM base WHERE order_status='delivered'
UNION ALL SELECT '3. con fecha de entrega y despacho',       COUNT(*) FROM base WHERE order_status='delivered'
        AND order_delivered_customer_date IS NOT NULL AND order_delivered_carrier_date IS NOT NULL
UNION ALL SELECT '4. fechas consistentes',                   COUNT(*) FROM base WHERE order_status='delivered'
        AND order_delivered_customer_date IS NOT NULL AND order_delivered_carrier_date IS NOT NULL
        AND order_delivered_carrier_date <= order_delivered_customer_date AND order_purchase_timestamp <= order_delivered_carrier_date
UNION ALL SELECT '5. + registro en fleet_deliveries e ítems (dataset final)', COUNT(*) FROM mv_dataset_analitico
""")
embudo["perdida"] = embudo.filas.diff().fillna(0).astype(int)
embudo["% sobre total"] = (100*embudo.filas/embudo.filas.iloc[0]).round(2)
embudo

                                                        paso  filas  perdida  % sobre total
0                                         1. Órdenes totales  99441        0         100.00
1                                      2. status = delivered  96478    -2963          97.02
2                         3. con fecha de entrega y despacho  96469       -9          97.01
3                                     4. fechas consistentes  96281     -188          96.82
4  5. + registro en fleet_deliveries e ítems (dataset final)  96281        0          96.82

In [7]:
# Controles de integridad del dataset final
chk = q("""
SELECT COUNT(*) AS filas, COUNT(DISTINCT order_id) AS ordenes_distintas,
       COUNT(*) FILTER (WHERE review_score IS NULL)            AS sin_resena,
       COUNT(*) FILTER (WHERE distancia_haversine_km IS NULL)  AS sin_haversine,
       COUNT(*) FILTER (WHERE flag_peso_imputado)              AS peso_imputado,
       MIN(fecha_compra) AS desde, MAX(fecha_compra) AS hasta
FROM mv_dataset_analitico""")
assert chk.filas[0] == chk.ordenes_distintas[0], "¡Fan-out! hay órdenes repetidas: revisar los JOIN"
print("OK: grano = 1 fila por orden")
chk.T

OK: grano = 1 fila por orden

                                     0
filas                            96281
ordenes_distintas                96281
sin_resena                         645
sin_haversine                      479
peso_imputado                       22
desde              2016-09-15 12:16:38
hasta              2018-08-29 15:00:37

## 4. Carga a pandas, tipos y flags de outliers
Los outliers **no se eliminan**: son entregas reales (p. ej. fletes altos en zonas remotas). Se **marcan** con la regla de Tukey (1.5·IQR) para decidir en cada análisis/modelo.

In [8]:
df = q("select * from mv_dataset_analitico")
cat_cols = ["estado_origen","estado_destino","categoria_principal","categoria_en","tipo_vehiculo","metodo_pago","delivery_status"]
for c in cat_cols: df[c] = df[c].astype("category")
for c in ["fecha_compra","mes_compra"]: df[c] = pd.to_datetime(df[c])
bool_cols = ["mismo_estado","flag_peso_imputado","demora_olist","tiene_comentario","resena_negativa"]
for c in bool_cols: df[c] = df[c].astype("boolean")
print(df.shape); df.dtypes.to_frame("dtype").T

(96281, 49)

,order_id,delivery_id,fecha_compra,mes_compra,anio,mes,dia_semana,estado_origen,estado_destino,mismo_estado,n_items,n_vendedores,categoria_principal,categoria_en,precio_total,flete_total,peso_total_g,flag_peso_imputado,flete_sobre_precio,pago_total,cuotas_max,metodo_pago,tipo_vehiculo,vehicle_id,driver_id,driver_behavior_score,fatigue_score_avg,indice_fatiga,distance_km,route_risk_level,traffic_congestion_level,weather_condition_severity,loading_unloading_time_h,eta_variation_hours,delivery_status,dias_entrega_total,dias_hasta_despacho,dias_transito,dias_prometidos,dias_demora_olist,demora_olist,distancia_haversine_km,review_score,tiene_comentario,n_resenas,resena_negativa,n_incidentes,horas_impacto_incidentes,dias_desde_ult_mant
dtype,object,int64,datetime64[ns],datetime64[ns],int64,int64,int64,category,category,boolean,int64,int64,category,category,float64,float64,float64,boolean,float64,float64,float64,category,category,int64,int64,float64,float64,float64,float64,float64,float64,float64,float64,float64,category,float64,float64,float64,float64,float64,boolean,float64,float64,boolean,int64,boolean,int64,float64,float64

### 4.1 Controles de coherencia de la flota sintética
Verifican sobre el dataset final lo que el generador garantiza por construcción. Si alguno falla, regenerar o reimportar la flota antes de seguir.

In [9]:
# delivery_status se deriva de la demora real de Olist: debe coincidir con demora_olist
assert ((df.delivery_status == "delayed") == df.demora_olist).all(), "delivery_status debería coincidir con demora_olist"
print("OK: delivery_status coincide con demora_olist (por construcción)")

# 1 conductor = 1 vehículo (vw_conductor reporta cuántos vehículos/tipos distintos usó cada conductor)
cond = q("""select count(*) as conductores,
                   count(*) filter (where vehiculos_distintos > 1 or tipos_vehiculo_distintos > 1) as incoherentes
            from vw_conductor where entregas > 0""")
print(cond.to_string(index=False))
assert cond.incoherentes[0] == 0, "Hay conductores con más de un vehículo o tipo de vehículo"

# Censura de las variables acotadas por el generador
eta = df.eta_variation_hours
print(f"eta_variation_hours: piso (-168) {100*(eta==-168).mean():.2f} % | techo (336) {100*(eta==336).mean():.2f} % | p95 = {eta.quantile(.95):.0f}")
print(f"distance_km en el piso (5 km): {100*(df.distance_km==5).mean():.2f} %")

OK: delivery_status coincide con demora_olist (por construcción)
 conductores  incoherentes
          95             0
eta_variation_hours: piso (-168) 1.29 % | techo (336) 5.14 % | p95 = 336
distance_km en el piso (5 km): 0.59 %

In [10]:
def flag_iqr(s, k=1.5):
    q1, q3 = s.quantile([.25,.75]); iqr = q3-q1
    return (s < q1-k*iqr) | (s > q3+k*iqr)

# Solo se marcan variables continuas sin cota. No se marcan eta_variation_hours (acotada y censurada en los límites)
# ni las variables simuladas con rango fijo y forma de U (tráfico, clima, riesgo), para las que la regla de Tukey no aplica.
vars_out = ["dias_entrega_total","dias_demora_olist","distance_km","flete_total","peso_total_g","precio_total"]
res = []
for v in vars_out:
    f = flag_iqr(df[v].dropna()); df[f"out_{v}"] = flag_iqr(df[v]).fillna(False)
    res.append((v, int(f.sum()), round(100*f.mean(),2)))
pd.DataFrame(res, columns=["variable","outliers_IQR","%"])

             variable  outliers_IQR      %
0  dias_entrega_total          4892   5.08
1   dias_demora_olist          4859   5.05
2         distance_km          7480   7.77
3         flete_total          9668  10.04
4        peso_total_g         13515  14.04
5        precio_total          7651   7.95

In [11]:
# Nulos remanentes en el dataset final (esperados: reseña y haversine)
nul = df.isna().sum(); nul = nul[nul>0].to_frame("nulos"); nul["%"] = (100*nul.nulos/len(df)).round(2)
nul

                        nulos     %
pago_total                  1  0.00
cuotas_max                  1  0.00
distancia_haversine_km    479  0.50
review_score              645  0.67
tiene_comentario          645  0.67
resena_negativa           645  0.67
dias_desde_ult_mant      2120  2.20

## 5. Exportación del dataset analítico

In [12]:
df.to_csv(OUT / "dataset_analitico.csv", index=False)
df.to_parquet(OUT / "dataset_analitico.parquet", index=False)
# Muestra top-1000 requerida por el entregable (reproducible)
df.sample(1000, random_state=42).sort_values("fecha_compra").to_csv(OUT / "dataset_analitico_muestra1000.csv", index=False)

# Vistas auxiliares para Etapa 3/4
q("select * from vw_flota_mes_tipo order by mes, tipo_vehiculo").to_csv(OUT / "flota_mes_tipo.csv", index=False)
q("select * from vw_conductor order by driver_id").to_csv(OUT / "conductores.csv", index=False)
print({p.name: f"{p.stat().st_size/1e6:.1f} MB" for p in OUT.glob("*") if p.is_file()})

{'.gitkeep': '0.0 MB', 'conductores.csv': '0.0 MB', 'dataset_analitico.csv': '33.7 MB', 'dataset_analitico.parquet': '9.1 MB', 'dataset_analitico_muestra1000.csv': '0.4 MB', 'diagnostico_calidad.csv': '0.0 MB', 'flota_mes_tipo.csv': '0.0 MB'}

## 6. Qué se hizo y por qué (para el informe)
| Decisión | Justificación |
|---|---|
| Grano = 1 fila por orden | `fleet_deliveries` es 1:1 con órdenes; ítems, pagos y reseñas son 1:N y se agregan para no inflar filas |
| Excluir órdenes sin entrega/fechas imposibles | No se puede calcular tiempo ni demora real |
| Peso 0/NULL → mediana de la categoría | Mantiene la regla de asignación de vehículo; se deja `flag_peso_imputado` |
| 1 reseña por orden (la más reciente) | Evita duplicados; `n_resenas` conserva la información |
| Centroide por zip con mediana y bounding box | 1M de puntos → 1 por zip, robusto a las 42 coordenadas erróneas |
| Outliers marcados, no eliminados | Son valores reales; el análisis decide si se winsoriza. Solo se marcan las variables continuas sin cota (los acotados y los simulados de rango fijo no) |
| Una sola definición de demora | `demora_olist` (entrega posterior a la fecha prometida) es la demora; `delivery_status` de la flota la replica por construcción |
| Variables operativas simuladas y condicionadas | Tráfico, clima, riesgo, conductor, incidentes y mantenimiento se generan a partir de señales reales (copula gaussiana, marginales de Kaggle): sus asociaciones son por diseño y se declaran como tales |
| `dias_desde_ult_mant` con nulos (≈ 2 %) | Órdenes anteriores al primer mantenimiento de su vehículo: se deja NULL y se imputa/indica en la Etapa 3 |